version: '2'

services:

  app:
    container_name: pluto-symfony3.app
    build: .docker/php
    volumes:
      - .:/app
      - ./var/logs:/app/var/logs
      - ./var/cache.:/app/var/cache

  nginx:
    container_name: pluto-symfony3.nginx
    build: .docker/nginx
    volumes_from:
      - app
    ports:
      - "5000:80"

  mariadb:
    image: mariadb
    container_name: pluto-symfony3.mariadb
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234