<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDjapf17\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDjapf17/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDjapf17.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDjapf17\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDjapf17\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Djapf17',
    'container.build_id' => 'a35d63f8',
    'container.build_time' => 1529849516,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDjapf17');
